# Generated by Django 5.0.1 on 2024-02-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenary_user_details',
            name='activity',
            field=models.CharField(max_length=300),
        ),
    ]
