# Generated by Django 4.2.7 on 2024-01-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkIN', models.DateField(blank=True, null=True)),
                ('checkOut', models.DateField(blank=True, null=True)),
                ('adult', models.IntegerField(blank=True, null=True)),
                ('Children', models.IntegerField(blank=True, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_reservations', to='travelapp.userlogin')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reservations', to='travelapp.userlogin')),
            ],
        ),
    ]
