# Generated by Django 5.0 on 2024-03-04 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='fullname',
            new_name='first_name',
        ),
    ]
