# Generated by Django 5.0.1 on 2024-02-03 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('days', models.IntegerField()),
                ('night', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='travelimages/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.category')),
            ],
        ),
    ]
