# Generated by Django 5.0.1 on 2024-02-24 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_alter_itenary_user_details_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itenary_user_details',
            name='itenary',
        ),
        migrations.AlterField(
            model_name='itenary_user_details',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.activities'),
        ),
    ]
