# Generated by Django 5.0.1 on 2024-01-27 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_alter_reservation_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='email',
        ),
    ]
