# Generated by Django 5.0.1 on 2024-01-21 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_alter_carbook_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelconfirm',
            old_name='hotel_id',
            new_name='hotel',
        ),
    ]
