# Generated by Django 5.0.1 on 2024-02-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='description',
            field=models.CharField(default='exit', max_length=2000),
            preserve_default=False,
        ),
    ]
