# Generated by Django 4.2.7 on 2024-01-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='email',
        ),
    ]
