# Generated by Django 5.0.1 on 2024-01-18 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_carview'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('carview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.carview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.userlogin')),
            ],
        ),
    ]
