# Generated by Django 5.0 on 2024-03-04 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_rename_fullname_userlogin_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='first_name',
            new_name='fullname',
        ),
    ]
