# Generated by Django 5.0.1 on 2024-02-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_places_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='category',
        ),
    ]
