# Generated by Django 5.0.1 on 2024-02-24 06:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_remove_itenary_user_details_itenary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Itenary_User_Details',
            new_name='Itinerary_User_Details',
        ),
    ]
