# Generated by Django 5.0.1 on 2024-01-27 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_remove_reservation_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='checkIN',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='checkOut',
            new_name='check_out',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='Children',
            new_name='children',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
