# Generated by Django 4.2.7 on 2024-01-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_remove_reservation_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='travelimages/')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
