# Generated by Django 5.0.1 on 2024-01-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_carbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbook',
            old_name='carview',
            new_name='car_id',
        ),
    ]
