# Generated by Django 5.0 on 2024-03-15 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_rename_first_name_userlogin_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbook',
            name='deposit',
        ),
    ]
