# Generated by Django 5.0.1 on 2024-02-06 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_remove_booking_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='travelimages/')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.places'),
        ),
        migrations.CreateModel(
            name='Itineary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('month', models.CharField(max_length=50)),
                ('day_of_week', models.CharField(max_length=50)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.hotel')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.places')),
            ],
        ),
        migrations.CreateModel(
            name='Itenary_User_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.activities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('itenary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.itineary')),
            ],
        ),
    ]
