# Generated by Django 5.0.1 on 2024-02-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_rename_itenary_user_details_itinerary_user_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbook',
            name='licesence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
