# Generated by Django 5.0.1 on 2024-01-27 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_rename_checkin_reservation_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='travelapp.reservation'),
        ),
    ]
