# Generated by Django 5.0.1 on 2024-01-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
    ]
