# Generated by Django 5.0 on 2024-02-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0007_itineary_user_details_delete_itinerary_user_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='distance',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
