# Generated by Django 5.0 on 2024-02-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0008_activities_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
