# Generated by Django 5.0.1 on 2024-02-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0009_alter_activities_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineary',
            name='meals',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
