# Generated by Django 5.0.1 on 2024-02-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0010_itineary_meals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itineary',
            old_name='place',
            new_name='package',
        ),
    ]
