# Generated by Django 5.0.1 on 2024-02-27 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0011_rename_place_itineary_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='itinerary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travelapp.itineary'),
        ),
    ]
