# Generated by Django 5.0.1 on 2024-02-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0014_rename_date_reservation_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
