# Generated by Django 5.0.1 on 2024-02-28 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0015_alter_reservation_arrival_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travelapp.booking'),
        ),
    ]
